language: cpp
before_install:
  - sudo apt-get install git cmake build-essential libx11-xcb-dev libxkbcommon-dev libmirclient-dev libwayland-dev libxrandr-dev
script:
  - cd VulkanTutorial/VulkanTutorial
  - g++ -std=c++11 -m64 -Wall -Wextra -Werror -I/C/VulkanSDK/1.0.3.1/Include *.cpp -o main
