language: cpp
before_install:
  - sudo apt-get install git cmake build-essential libx11-xcb-dev libxkbcommon-dev libmirclient-dev libwayland-dev libxrandr-dev
script:
  - cd VulkanTutorial/VulkanTutorial
  - gcc -m64 -I/C/VulkanSDK/1.0.3.1/Include -std=c11 stdafx.cpp VulkanTutorial.cpp VulkanHandler.cpp ErrorHandler.cpp ConsoleHandler.cpp -o main
